### ISSUE TITLE
Migrate the CI service

### ISSUE THREAD

**Issue by movermeyer** [mc706/changelog-cli#25]
[travis-ci._**org**_](https://www.travis-ci.org/) is shutting down soon, and has stopped doing builds for `mc706/changelog-cli`.

We have to migrate to a different system.

While we could migrate to the new [travis-ci._**com**_](https://www.travis-ci.com) (which is configured using GitHub Actions), I would prefer to migrate to something else:

In order of preference
1. GitHub Actions itself
2. CircleCI
3. TravisCI

I have experience with GitHub Actions and CircleCI for other projects.

* [Here is an example](https://github.com/movermeyer/backports.datetime_fromisoformat/blob/master/.github/workflows/test.yml) of a simple build I use GitHub Actions for.
* [Here is an example](https://github.com/closeio/ciso8601/blob/master/.circleci/config.yml) of a more complicated project that I use CircleCI for. I would use GitHub Actions for this too, but it will soon be a much more complicated build (once I add binary wheels; but that's another story)

**Comment by mc706** [comment]
All for trying out github actions. I have actually moved almost all of  my other open source pypi projects to gitlab _because_ of the easier CI environment so I would love to see it done well in github to be able to compare.
