### ISSUE TITLE
format of version and date line

### ISSUE THREAD

**Issue by schunka** [mc706/changelog-cli#29]
Hello,
this is great tool and until recently I've got no trouble using it.
But this line:
https://github.com/mc706/changelog-cli/blob/e7d8293e5f76e0fff3fa7fbf55781503f729b315/src/changelog/templates.py#L9
caused trouble in our pipeline. One part of the pipeline is checking version number in CHANGELOG.md (created by changelog-cli), and it follows format from `keepachangelog.com`. And when it tries to read a version it fails as the regex expects `[` and `]` around version number.
changelog-cli obviously knows about square braces:
https://github.com/mc706/changelog-cli/blob/e7d8293e5f76e0fff3fa7fbf55781503f729b315/src/changelog/templates.py#L14
Is it possible to change `RELEASE_LINE` format or use the `RELEASE_LINE` format gahtered from CHANGELOG.md itself. eg. which regex matches the version that format will be used...

**Comment by mbcko** [comment]
This is something that bothers us as well. It's a paradox - this tool declares that it is based on the format specified on `keepachangelog.com`, where they use `## [1.0.0] - 2017-06-20` format. But the default format used by this tool is different.

**Comment by vacajakub** [comment]
It is really annoying..we have to change format manually after every release.
