### ISSUE TITLE
How to actually run it?

### ISSUE THREAD

**Issue by crobarcro** [mc706/changelog-cli#9]
I installed this helpful looking project va pip, but how do I actually invoke it in the way shown in your readmes?

`changelog` is not a program on my computers path, and that's not valid python syntax, so how are you running it exactly?

**Comment by movermeyer** [comment]
`changelog` is installed into the `bin` directory of your Python installation.

* In `virtualenv`'s , this is `env/bin/changelog` (or `env/Scripts/python.exe` on Windows).
* In Windows (for Python 3.9), it is `C:\Users\Mike\AppData\Local\Programs\Python\Python39\Scripts`
* On Ubuntu, it was installed to `~/.local/bin/`

Hope that helps
